### ISSUE TITLE
Retrieval practice

### ISSUE THREAD

**Issue by Eefscheerlinck** [otacke/h5p-cornell#31]
It would be nice if, after the student made the notes, to give the option to hide the notes and to use only the cues as a way for retrieval practice (e.g.  a button for the student to toggle the visibility of their own notes).

**Comment by otacke** [comment]
@Eefscheerlinck 

I have added the feature that you requested in https://github.com/otacke/h5p-cornell/commit/5066b31aa522a9145f91cb580a9cb5716c440ddf, so I will close this issue here.

I have created a ticket for the H5P core team at https://h5ptechnology.atlassian.net/browse/HFP-2828 asking for a release of the changes. I cannot tell, however, when they are going to work on the ticket. You can track the progress and the status there. If you need that feature right now, feel free to build a library file from the sources and to install that on your platform.
